In [1]:
import pandas as pd

In [2]:
df_content = pd.read_csv(r"C:\Users\tejasvi chaturvedi\Downloads\Content.csv")
df_reaction = pd.read_csv(r"C:\Users\tejasvi chaturvedi\Downloads\Reactions.csv")
df_reactiont = pd.read_csv(r"C:\Users\tejasvi chaturvedi\Downloads\ReactionTypes.csv")

In [11]:
df_content

,Content ID,User ID,Type,Category,URL
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/9f7...
2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/230...
3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology,https://socialbuzz.cdn.com/content/storage/356...
4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food,https://socialbuzz.cdn.com/content/storage/01a...
...,...,...,...,...,...
995,b4cef9ef-627b-41d7-a051-5961b0204ebb,5b62e10e-3c19-4d28-a57c-e9bdc3d6758d,video,public speaking,NaN
996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology,https://socialbuzz.cdn.com/content/storage/7a7...
997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism,https://socialbuzz.cdn.com/content/storage/435...
998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture,https://socialbuzz.cdn.com/content/storage/4e4...
999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

In [13]:
df_content.drop('User ID',axis='columns',inplace=True)

In [14]:
df_content

,Content ID,Type,Category,URL
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/9f7...
2,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/230...
3,356fff80-da4d-4785-9f43-bc1261031dc6,photo,technology,https://socialbuzz.cdn.com/content/storage/356...
4,01ab84dd-6364-4236-abbb-3f237db77180,video,food,https://socialbuzz.cdn.com/content/storage/01a...
...,...,...,...,...
995,b4cef9ef-627b-41d7-a051-5961b0204ebb,video,public speaking,NaN
996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,GIF,technology,https://socialbuzz.cdn.com/content/storage/7a7...
997,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,https://socialbuzz.cdn.com/content/storage/435...
998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,https://socialbuzz.cdn.com/content/storage/4e4...
999,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

In [15]:
df_content.isnull().sum()

Content ID      0
Type            0
Category        0
URL           199
dtype: int64

In [16]:
df_content1 = df_content.dropna()

In [17]:
df_content1

,Content ID,Type,Category,URL
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/9f7...
2,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/230...
3,356fff80-da4d-4785-9f43-bc1261031dc6,photo,technology,https://socialbuzz.cdn.com/content/storage/356...
4,01ab84dd-6364-4236-abbb-3f237db77180,video,food,https://socialbuzz.cdn.com/content/storage/01a...
...,...,...,...,...
994,c54b49c4-b1f2-4641-8595-1cbd19937845,photo,science,https://socialbuzz.cdn.com/content/storage/c54...
996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,GIF,technology,https://socialbuzz.cdn.com/content/storage/7a7...
997,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,https://socialbuzz.cdn.com/content/storage/435...
998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,https://socialbuzz.cdn.com/content/storage/4e4...
999,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

In [18]:
df_reaction

,Unnamed: 0,Content ID,User ID,Type,Datetime
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,NaN,NaN,2021-04-22 15:17:15
1,1,97522e57-d9ab-4bd6-97bf-c24d952602d2,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
2,2,97522e57-d9ab-4bd6-97bf-c24d952602d2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
3,3,97522e57-d9ab-4bd6-97bf-c24d952602d2,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
4,4,97522e57-d9ab-4bd6-97bf-c24d952602d2,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
...,...,...,...,...,...
25548,25548,75d6b589-7fae-4a6d-b0d0-752845150e56,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
25549,25549,75d6b589-7fae-4a6d-b0d0-752845150e56,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
25550,25550,75d6b589-7fae-4a6d-b0d0-752845150e56,NaN,interested,2020-09-12 03:54:58
25551,25551,75d6b589-7fae-4a6d-b0d0-752845150e56,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
25552,25552,75d6b589-7fae-4a6d-b0d0-752845150e56,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [20]:
df_reaction = df_reaction.drop(['User ID','Unnamed: 0','Datetime'],axis='columns')

In [21]:
df_reaction

                                 Content ID        Type
0      97522e57-d9ab-4bd6-97bf-c24d952602d2         NaN
1      97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust
2      97522e57-d9ab-4bd6-97bf-c24d952602d2     dislike
3      97522e57-d9ab-4bd6-97bf-c24d952602d2      scared
4      97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust
...                                     ...         ...
25548  75d6b589-7fae-4a6d-b0d0-752845150e56     dislike
25549  75d6b589-7fae-4a6d-b0d0-752845150e56   intrigued
25550  75d6b589-7fae-4a6d-b0d0-752845150e56  interested
25551  75d6b589-7fae-4a6d-b0d0-752845150e56     worried
25552  75d6b589-7fae-4a6d-b0d0-752845150e56     cherish

[25553 rows x 2 columns]

In [23]:
df_reaction.isnull().sum()

Content ID      0
Type          980
dtype: int64

In [24]:
df_reaction1 = df_reaction.dropna()

In [25]:
df_reaction1

                                 Content ID        Type
1      97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust
2      97522e57-d9ab-4bd6-97bf-c24d952602d2     dislike
3      97522e57-d9ab-4bd6-97bf-c24d952602d2      scared
4      97522e57-d9ab-4bd6-97bf-c24d952602d2     disgust
5      97522e57-d9ab-4bd6-97bf-c24d952602d2  interested
...                                     ...         ...
25548  75d6b589-7fae-4a6d-b0d0-752845150e56     dislike
25549  75d6b589-7fae-4a6d-b0d0-752845150e56   intrigued
25550  75d6b589-7fae-4a6d-b0d0-752845150e56  interested
25551  75d6b589-7fae-4a6d-b0d0-752845150e56     worried
25552  75d6b589-7fae-4a6d-b0d0-752845150e56     cherish

[24573 rows x 2 columns]

In [26]:
df_reaction1.Type.unique()

array(['disgust', 'dislike', 'scared', 'interested', 'peeking', 'cherish',
       'hate', 'love', 'indifferent', 'super love', 'intrigued',
       'worried', 'like', 'heart', 'want', 'adore'], dtype=object)